SharePi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
]


web/urls.py
from django.urls import path
from .views import index, file_form, file_post, file_view, request_access

app_name = "web"

urlpatterns = [
    path(r'', index, name='index'),
    path(r'upload', file_form, name='file_form'),
    path(r'upload_post', file_post, name='file_post'),
    path(r'view', file_view, name='file_view'),
    path(r'verification', request_access, name='request_access')
]

web/models.py
from django.db import models

# Create your models here.

class File(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True)
    file = models.FileField(blank=True)

web/forms.py
from django import forms
from django.forms import ModelForm
from .models import File


class FileCreationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FileCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = File
        fields = '__all__'

web/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from .forms import FileCreationForm
from .models import File
import subprocess

# Create your views here.

granted_access = []
waiting_access = []

def index(request):
    
    ip = request.META['REMOTE_ADDR']
    ip = ip.replace(".","")
    #ip, is_routable = get_client_ip(request)
    ip = ip.replace(".","")
    if(ip in granted_access):
        return render(request, 'index.html', {})
    elif(ip not in waiting_access):
        waiting_access.append(ip)
    import pyqrcode
    qr = pyqrcode.create(ip)
    qr.png("/var/www/sharepi-web-app/static/images/qrcode.png", scale=6)
    return render(request, 'index.html', {"file":"qrcode.png"})

def file_form(request):
    ip = request.META['REMOTE_ADDR']
    ip = ip.replace(".","")
    if(ip in granted_access):
        return render(request, 'form.html', {'form': FileCreationForm})
    else:
        return HttpResponseRedirect("/")
        
def file_post(request):
    if request.method == 'POST':
        the_file = File(name=request.POST['name'], file=request.FILES['file'])
        the_file.save()
    return HttpResponseRedirect('/')

def file_view(request):
    return render(request, 'list.html', {})

def request_access(request):
    code = request.GET["code"]
    if(code in  waiting_access):
        granted_access.append(code)
        waiting_access.remove(code)
        response = {"status" : "success"}
    else:
        response = {"status" : "failed"}
    return JsonResponse(response)

web/templates/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>
  <body>
    <form id="form" method="POST" enctype="multipart/form-data" action="{% url 'web:file_post' %}">
    <h1>File Upload</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
    </form>
  </body>
</html>

web/templates/index.html
{% load staticfiles %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style type="text/css">

    </style>
  </head>
  <body>
    <h1>SharePi</h1>
    <p>
      SharePi adalah aplikasi yang terbenam pada Raspberry Pi untuk berbagi konten pada satu jaringan
      LAN.
    </p>
    {% if file %}
    <p>Untuk mendapat akses upload, scan QR Code dibawah ini ke device</p>
    <p>Refresh setelah sukses melakukan verifikasi (lampu hijau)</p>
    <img src="{% static 'images/qrcode.png' %}" width=350px height=350px alt="gada">
    {% else %}
    <a href="{% url 'web:file_form' %}">Klik disini</a> untuk mulai berbagi
    {% endif %}
    <br>
    <a href="/storage">Klik disini</a> untuk melihat library
  </body>
</html>

web/templates/list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>
  <body>
    <h1>Hello, Raspberry Pi!</h1>
  </body>
</html>